using System.Text;

namespace SimpleMediator.SourceGenerator;

/// <summary>
/// Renders generated sources. Output is C# 7.3 compatible (block namespaces, no nullable
/// annotations) and fully qualified, so it compiles in any consumer regardless of language
/// version, usings or type-name collisions.
/// </summary>
internal static class Emitter
{
    private const string Registry = "global::SimpleMediator.Generated.GeneratedMediatorRegistry";
    private const string Services = "global::Microsoft.Extensions.DependencyInjection.IServiceCollection";

    internal static readonly string GeneratedCodeAttribute =
        "[global::System.CodeDom.Compiler.GeneratedCode(\"SimpleMediator.SourceGenerator\", \"" +
        typeof(Emitter).Assembly.GetName().Version + "\")]";

    public static readonly string EntryPoint = $$"""
        // <auto-generated/>
        namespace SimpleMediator
        {
            /// <summary>
            /// Reflection-free SimpleMediator registration generated at compile time. Compatible with
            /// trimming and Native AOT.
            /// </summary>
            {{GeneratedCodeAttribute}}
            internal static partial class SimpleMediatorGeneratedExtensions
            {
                /// <summary>
                /// Registers the mediator with default options. Like <c>AddSimpleMediator()</c>, no handler is
                /// registered until an assembly is passed to <c>RegisterAssembly</c>.
                /// </summary>
                public static {{Services}} AddSimpleMediatorGenerated(this {{Services}} services)
                {
                    return global::SimpleMediator.Generated.GeneratedMediatorRegistration.Register(services, null, Populate);
                }

                /// <summary>
                /// Registers the mediator with handlers, behaviors and dispatch discovered at compile time.
                /// Configure it exactly like <c>AddSimpleMediator</c>: <c>RegisterAssembly(typeof(T).Assembly)</c>
                /// selects the scanned assemblies and <c>AddBehavior(typeof(B&lt;,&gt;))</c> enables behaviors.
                /// </summary>
                public static {{Services}} AddSimpleMediatorGenerated(this {{Services}} services, global::System.Action<global::SimpleMediator.SimpleMediatorOptions> configure)
                {
                    if (configure == null)
                    {
                        throw new global::System.ArgumentNullException(nameof(configure));
                    }

                    return global::SimpleMediator.Generated.GeneratedMediatorRegistration.Register(services, configure, Populate);
                }

                private static void Populate({{Registry}} registry)
                {
                    PopulateCore(registry);
                }

                static partial void PopulateCore({{Registry}} registry);
            }
        }

        """;

    public static string EmitRegistrations(RegistrationModel model)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#pragma warning disable");
        builder.AppendLine("namespace SimpleMediator");
        builder.AppendLine("{");
        builder.AppendLine("    internal static partial class SimpleMediatorGeneratedExtensions");
        builder.AppendLine("    {");
        builder.Append("        static partial void PopulateCore(").Append(Registry).AppendLine(" registry)");
        builder.AppendLine("        {");

        foreach (var assembly in model.Assemblies)
        {
            Line(builder, "registry.AddAssembly(" + assembly + ");");
        }

        foreach (var (request, response) in model.Requests)
        {
            Line(builder, "registry.AddRequest<" + request + ", " + response + ">();");
        }

        foreach (var notification in model.Notifications)
        {
            Line(builder, "registry.AddNotification<" + notification + ">();");
        }

        foreach (var handler in model.Handlers)
        {
            Line(builder, "registry.AddHandler<" + handler.Service + ", " + handler.Implementation + ">(typeof(" + handler.Key + "));");
        }

        foreach (var behavior in model.Behaviors)
        {
            Line(builder, "registry.AddBehavior<" + behavior.Service + ", " + behavior.Implementation + ">(typeof(" + behavior.Key + "));");
        }

        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void Line(StringBuilder builder, string statement)
        => builder.Append("            ").AppendLine(statement);
}
