<Project>

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>default</LangVersion>
    <Deterministic>true</Deterministic>

    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest</AnalysisLevel>
    <RollForward Condition="'$(MSBuildProjectName)' != 'SimpleMediator'">Major</RollForward>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(MSBuildProjectName)' == 'SimpleMediator'">
    <IsPackable>true</IsPackable>
    <AnalysisMode>All</AnalysisMode>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnablePackageValidation>true</EnablePackageValidation>

    <PackageId>s4ndr0ne.SimpleMediator</PackageId>
    <VersionPrefix Condition="'$(VersionPrefix)' == ''">0.0.0</VersionPrefix>
    <VersionSuffix Condition="'$(VersionSuffix)' == ''">local</VersionSuffix>
    <Authors>s4ndr0ne</Authors>
    <Description>A simple mediator implementation for .NET</Description>
    <Copyright>Copyright © s4ndr0ne</Copyright>
    <PackageReleaseNotes>See CHANGELOG.md for release history.</PackageReleaseNotes>
    <RepositoryUrl>https://github.com/s4ndr0ne/SimpleMediator</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <PackageTags>mediator, pattern, net8, net10</PackageTags>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

</Project>
