<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.PublicApiAnalyzers" PrivateAssets="all" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SimpleMediator.Tests" />
    <InternalsVisibleTo Include="SimpleMediator.SafetyTests" />
    <InternalsVisibleTo Include="SimpleMediator.Benchmarks" />
  </ItemGroup>

  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)../../LICENSE" Pack="true" PackagePath="" />
    <None Include="$(MSBuildThisFileDirectory)../../README.md" Pack="true" PackagePath="" />
    <None Include="$(MSBuildThisFileDirectory)../../CHANGELOG.md" Pack="true" PackagePath="" />
  </ItemGroup>

</Project>
